openapi: 3.1.3
info:
  title: Product Service API
  description: API for the shoppe
  version: 1.0.0
  contact:
    name: Jane

servers:
  - url: https://{apiId}.execute-api.{region}.amazonaws.com/{stage}
    variables:
      apiId:
        default: 6t7fhbiyr6
        description: API Gateway ID
      region:
        default: us-east-2
        description: AWS Region
      stage:
        default: prod
        description: API Stage

paths:
  /products:
    get:
      summary: Get all products
      description: Returns a list of all products
      operationId: getProductsList
      tags:
        - products
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
                  statusCode:
                    type: integer
                    example: 200
        '500':
          $ref: '#/components/responses/InternalServerError'

  /products/{productId}:
    get:
      summary: Get product by ID
      description: Returns a single product by its ID
      operationId: getProductById
      tags:
        - products
      parameters:
        - name: productId
          in: path
          description: ID of the product to retrieve
          required: true
          schema:
            type: string
            example: "7567ec4b-b10c-48c5-9345-fc73c48a80aa"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Product'
                  statusCode:
                    type: integer
                    example: 200
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    Product:
      type: object
      required:
        - id
        - title
        - description
        - price
        - count
      properties:
        id:
          type: string
          example: "7567ec4b-b10c-48c5-9345-fc73c48a80aa"
        title:
          type: string
          example: "ProductOne"
        description:
          type: string
          example: "Short Product Description1"
        price:
          type: integer
          minimum: 0
          example: 24
        count:
          type: integer
          minimum: 0
          example: 4
        image:
          type: string
          format: uri
          example: "https://example.com/product-image.jpg"

    Error:
      type: object
      required:
        - message
        - statusCode
      properties:
        message:
          type: string
        statusCode:
          type: integer
        error:
          type: object
          properties:
            code:
              type: string
            productId:
              type: string
            details:
              type: string

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Bad Request: Missing or invalid productId parameter"
              statusCode:
                type: integer
                example: 400
              error:
                type: object
                properties:
                  code:
                    type: string
                    example: "INVALID_REQUEST"

    NotFound:
      description: Product not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Product not found"
              statusCode:
                type: integer
                example: 404
              error:
                type: object
                properties:
                  code:
                    type: string
                    example: "PRODUCT_NOT_FOUND"
                  productId:
                    type: string
                    example: "7567ec4b-b10c-48c5-9345-fc73c48a80aa"

    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Internal server error"
              statusCode:
                type: integer
                example: 500
              error:
                type: object
                properties:
                  code:
                    type: string
                    example: "INTERNAL_SERVER_ERROR"
                  details:
                    type: string
                    example: "Error details message"

  securitySchemes:
    CORSAuth:
      type: apiKey
      name: Access-Control-Allow-Origin
      in: header

security:
  - CORSAuth: []

tags:
  - name: products
    description: Operations about products
